### ISSUE TITLE
why there exist two different solver.prototxt

### ISSUE THREAD

**Issue by yaoqi-zd** [speedinghzl/DSRG#1]
In the experiment folder, there exist two different solver.prototxt: solver-f and solver-s, may I ask how to use them? 
solver-s seems use the 41x41 seeds for training, while solver-f seems to use the DSRG output for training.
Is solver-s represents the main procedure to train DSRG, and solver-f means 'Retrain' procedure refered in your paper?
THX!

**Comment by speedinghzl** [comment]
@yaoqi-zd Yes, you are right. The whole training procedure contains DSRG training and retrain procedure. You can find the script in [run.sh](https://github.com/speedinghzl/DSRG/blob/master/training/experiment/seed_mc/run.sh).
