### ISSUE TITLE
Comprehension of pretrained VGG16 model

### ISSUE THREAD

**Issue by mangoyuan** [speedinghzl/DSRG#12]
很好的工作！在使用预训练vgg16的权值时，我发现deploy.prototxt里面包含了ASPP模块，而原始VGG16并不包含这部分。所以我想知道预训练的权值具体是怎么得到的？谢谢！

**Comment by speedinghzl** [comment]
将原始deeplab提供的[vgg16](http://www.cs.jhu.edu/~alanlab/ccvl/init_models/vgg16_20M.caffemodel)中的fc6-7复制多份作为ASPP的初始权重。

**Comment by mangoyuan** [comment]
非常感谢！最近想用pytorch复现一下，发现pytorch的初始权重挺难找的。

**Comment by zmll** [comment]
> 很好的工作！在使用预训练vgg16的权值时，我发现deploy.prototxt里面包含了ASPP模块，而原始VGG16并不包含这部分。所以我想知道预训练的权值具体是怎么得到的？谢谢！
  @speedinghzl    @mangoyuan  你好，请问  vgg16_20M_mc.caffemodel  这个模型怎么得来的？就只需要在Imagenet上训练吗？
