### ISSUE TITLE
Loss calculation is too slow

### ISSUE THREAD

**Issue by yassouali** [speedinghzl/DSRG#18]
Hi,

First of all, thank you very much for providing the implementation of your paper.
I am trying to recreate the results in PyTorch, but I have very slow training time due to the consistency loss computation, which uses pydensecrf, and it takes a lot of time for a moderately sized images (~ 356).
Do you have any recommendations on how to speed things up, and can you please provide the time it took to train the network for in your case.

Thank you very much.

**Comment by speedinghzl** [comment]
Please refer to GPU version dense CRF.
https://github.com/heiwang1997/DenseCRF. Hope it helps.

**Comment by yassouali** [comment]
Thank you very much, I see that the code is in C++, so I need to port it to python is that right, anyhow, thank you.
