### ISSUE TITLE
Failed to install CRF

### ISSUE THREAD

**Issue by laukun** [speedinghzl/DSRG#2]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\appdata\local\continuum\anaconda3\libs /LIBPATH:c:\users\appdata\local\continuum\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64" /EXPORT:PyInit_krahenbuhl2013/wrapper build\temp.win-amd64-3.5\Release\krahenbuhl2013/wrapper.obj build\temp.win-amd64-3.5\Release\src/densecrf.obj build\temp.win-amd64-3.5\Release\src/labelcompatibility.obj build\temp.win-amd64-3.5\Release\src/pairwise.obj build\temp.win-amd64-3.5\Release\src/permutohedral.obj build\temp.win-amd64-3.5\Release\src/unary.obj build\temp.win-amd64-3.5\Release\src/util.obj build\temp.win-amd64-3.5\Release\src/densecrf_wrapper.obj /OUT:build\lib.win-amd64-3.5\krahenbuhl2013/wrapper.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\krahenbuhl2013\wrapper.cp35-win_amd64.lib
    LINK : error LNK2001: unresolved external symbol PyInit_krahenbuhl2013/wrapper
    build\temp.win-amd64-3.5\Release\krahenbuhl2013\wrapper.cp35-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "c:\users\appdata\local\continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-req-build-1u64fmyp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AppData\Local\Temp\pip-record-blyy3smc\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AppData\Local\Temp\pip-req-build-1u64fmyp\

**Comment by speedinghzl** [comment]
@laukun This code has only been tested on Linux (Ubuntu 14.04). Please use the same operating system to compile CRF.

**Comment by laukun** [comment]
Ok, thank you.
