### ISSUE TITLE
comprehension of DSRG 

### ISSUE THREAD

**Issue by DQDH** [speedinghzl/DSRG#9]
你好, @speedinghzl ，我想问一下，在网络训练过程中，每一次迭代是使用上一次训练后扩展的种子区域作为初始种子区域来不断更新初始种子区域，还是初始种子区域一直保持不变，只是在每次迭代训练网络时，在DSRG层根据初始种子进行生长作为标签计算seed loss？

**Comment by speedinghzl** [comment]
We always use the seed cues generated by CAM as the initial seed for region growing in each iteration.

**Comment by DQDH** [comment]
Thanks！
